name: Data WP

on:
  schedule:
    - cron: '0 6,18 * * *'  # Run at 6 AM and 6 PM UTC
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  generate-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to prevent push issues

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate Data
        run: node api/wp/index.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"

          git pull --rebase origin main  # Pull latest changes before pushing
          git add api/wp/wapo_graphics_feed.json
          
          if [[ `git status --porcelain` ]]; then
            echo "OK: Changes detected."
            git commit -m "gh-action get wapo data: $(date -u)"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/iguacel/graphics-feed.git main
          else
            echo "ðŸ“„ No changes detected, skipping push."
          fi
